export const DEFAULT_GUI_CONFIG = {
  workerUrl: '',
  daemonSecret: '',
  deviceId: '',
  deviceName: '',
  deviceFingerprint: '',
  tunnelEnabled: true,
  tunnelPublicUrl: '',
  tunnelToken: '',
  tunnelName: '',
  quickTunnel: true,
  tunnelLogLevel: 'info',
  r2Endpoint: '',
  r2BucketName: '',
  r2AccessKeyId: '',
  r2SecretAccessKey: '',
  llmBaseUrl: 'http://localhost:11434/v1',
  llmApiKey: 'ollama',
  llmModel: 'qwen2.5:7b',
  llmVisionCapable: true,
  llmMaxTokens: 180,
  llmPrompt: 'You are labeling a private photography gallery. Return compact JSON only, with this exact shape: {"description":"...","tags":["#..."]}. Use Simplified Chinese. The description must be one complete, natural sentence, specific to the image, preferably 30 to 70 Chinese characters. Do not cut the sentence off mid-thought. Create 1 to 4 elegant, specific tags; each tag must start with #, contain no spaces, and be useful for search. No markdown, no extra text.',
  llmTimeoutMs: 30000,
  syncConcurrency: 4,
  processConcurrency: 2,
  autoStart: true
} as const;
